### ISSUE TITLE
libby seems to be down when searching?

### ISSUE THREAD

**Issue by ryan-c-dev** [carterprince/libby#18]
Have tested on WSL2 in Windows11, and Artix LInux, with same results, no books seem to come up as before. I've done both single quotes, double quotes and no quotes. Will always say no result.

**Comment by carterprince** [comment]
Thanks, I just pushed a commit that should fix this.

It was either due to the fact that `libgen.gs` was taken down, the code for fetching the table became obsolete, or possibly both.

It should work now, though. Let me know if not.

**Comment by carterprince** [comment]
Will fix soon, bear with me.

**Comment by ryan-c-dev** [comment]
*sorry a better error, after searching for huckleberry finn, could be url?:*

Traceback (most recent call last):
  File "/usr/bin/libby", line 192, in <module>
Traceback (most recent call last):
  File "/usr/bin/libby", line 192, in <module>
    main()
    main()
  File "/usr/bin/libby", line 189, in main
  File "/usr/bin/libby", line 189, in main
    download(query, options)
    download(query, options)
  File "/usr/bin/libby", line 138, in download
  File "/usr/bin/libby", line 138, in download
    mirror_response = requests.get(selected_book["mirror"], headers=headers)
    mirror_response = requests.get(selected_book["mirror"], headers=headers)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in
request
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in
request
    return session.request(method=method, url=url, **kwargs)
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 575,
in request
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 575,
in request
    prep = self.prepare_request(req)
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 486,
in prepare_request
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 486,
in prepare_request
    p.prepare(
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 368, in
prepare
    p.prepare(
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 368, in
prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 439, in
prepare_url
    self.prepare_url(url, params)
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 439, in
prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL
'/ads82bf93b66f2f7bd69ced90eb297be2f8HKYBJ1NT': No scheme supplied. Perhaps
you meant https:///ads82bf93b66f2f7bd69ced90eb297be2f8HKYBJ1NT?
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL
'/ads82bf93b66f2f7bd69ced90eb297be2f8HKYBJ1NT': No scheme supplied. Perhaps
you meant https:///ads82bf93b66f2f7bd69ced90eb297be2f8HKYBJ1NT?

**Comment by carterprince** [comment]
Okay, the issue should be resolved now.

Reinstall and let me know if it's working for you.
